jobs:
  include:
    -
      name: Ubuntu 18.04
      dist: bionic
      language: python
      python:
        - "3.6"
      cache:
        directories:
          - "~/.platformio"
      addons:
        apt:
          packages: [ "libsdl2-dev:i386", gcc-multilib, g++-multilib ]
      install:
        - pip install -U platformio
        - platformio update
      script:
        # Test builds status
        - platformio run -e native
        - platformio run -e stm32f429_disco
        # Tests not available now
        #- platformio test -e native
    -
      name: macOS 10.14
      os: osx
      osx_image: xcode11.3
      language: shell
      cache:
        directories:
          - "~/.platformio"
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2
      install:
        - sudo easy_install pip # TODO: remove after https://travis-ci.community/t/missed-pip-after-xcode-image-update/7802 fixed
        - pip install --upgrade pip
        - pip install -U platformio
        - platformio update
      script:
        # Test builds status
        - platformio run -e native
        - platformio run -e stm32f429_disco
    -
      name: Windows
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        - |-
          [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          choco uninstall -y mingw
          choco upgrade --no-progress -y msys2
          export msys2='cmd //C RefreshEnv.cmd '
          export msys2+='& set MSYS=winsymlinks:nativestrict '
          export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
          export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
          export msys2+=" -msys2 -c "\"\$@"\" --"
          $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain mingw-w64-x86_64-SDL2
          taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
          export MAKE=mingw32-make  # so that Autotools can find it

      env: PATH=/c/Python36:/c/Python36/Scripts:/C/tools/msys64/mingw64/bin:$PATH
      before_cache:
        - $msys2 pacman --sync --clean --noconfirm
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
          - /C/tools/msys64      
      install:
        - pip install -U platformio
        - platformio update
      script:
        # Test builds status (bare metal only)
        - platformio run -e native
        - platformio run -e stm32f429_disco
